BaseUrl= "http://kyleandarica.com/"
LanguageCode= "en-EN"
Title= "The Crazy World of Riley, Arica and Kyle"
paginate = 5
DisqusShortname = "kyleandarica"
Copyright = "All rights reserved - 2017"
canonifyurls = true
theme = "casper"

[params]
  description = ""
  cover = "img/header-image.jpg"
  author = ""
  #authorlocation = "Maryland"
  authorwebsite = ""
  share = false
  bio= ""
  logo = ""
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true

[[menu.main]]
  name = "Safe Foods"
  weight = -120
  identifier = "safe-foods"
  url = "/info/safe-foods"

[[menu.main]]
  name = "Blog"
  weight = -110
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Photos"
  weight = -100
  identifier = "photos"
  url = "http://photos.kyleandarica.com"