BaseUrl= "http://kyleandarica.com/"
LanguageCode= "en-EN"
Title= "The crazy world of Riley, Arica and Kyle"
paginate = 5
DisqusShortname = "kyleandarica"
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme = "casper"

[params]
  description = ""
  cover = "img/header-image.jpg"
  author = ""
  #authorlocation = "Maryland"
  authorwebsite = ""
  share = false
  bio= ""
  logo = ""
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
